package mouse_control.view {
	import flash.display.DisplayObjectContainer;

	/* Would idealy be implemented in CursorGraphics, But the fact that frames
	 * are generated by the flash file would make using the gotoAndStop function illegal.
	 */
	public class CursorMovieClipView implements CursorView {
		private var graphics:CursorGraphics = new CursorGraphics();
		
		public function displayOnto(container:DisplayObjectContainer):void {
			container.addChild(graphics);
		}
		
		public function pieceSelected():Boolean {
			return graphics.currentFrame == 2;
		}
		
		public function setSelected():void {
			graphics.gotoAndStop(2);
		}
		
		public function setNotSelected():void {
			graphics.gotoAndStop(1);
		}
		
		public function set x(value:Number):void {
			graphics.x = value;
		}
		
		public function set y(value:Number):void {
			graphics.y = value;
		}
		
		public function get x():Number {
			return graphics.x;
		}
		
		public function get y():Number {
			return graphics.y;
		}
		
		public function show():void {
			graphics.visible = true;
		}
		
		public function hide():void {
			graphics.visible = false;
		}
		
		public function get visible():Boolean {
			return graphics.visible;
		}
	}
}